### ISSUE TITLE
malformed FASTQ file

### ISSUE THREAD

**Issue by jtackm** [BioJulia/FASTX.jl#48] opened 2021-05-25 13:02 UTC
Hi,

I started using FASTX today and ran into the following issue.

## Expected Behavior
I unzipped [sra_data.fastq.gz](https://github.com/BioJulia/FASTX.jl/files/6539404/sra_data.fastq.gz) and wanted to read it record by record via

```
r = FASTX.FASTQ.Reader(open("sra_data.fastq"))
for record in r
<do stuff>
end
```

## Current Behavior
However, I'm getting the following error message: `ArgumentError: malformed FASTQ file at line 367849`. I looked at the corresponding line but could not spot any abvious problems.

## Context
Among other things, I will be converting the FASTQ records into FASTA records eventually.

## Your Environment

- Package Version used: v1.1.1
- Julia Version used: 1.6
- Operating System and version (desktop or mobile): Ubuntu (20.04.1)

**Comment by jakobnissen** [comment] 2021-05-25 14:19
The issue is that the file ends with two trailing newlines. I will draft a PR to ignore any trailing whitespace shortly. Until then, you can manually remove the final newline from the file.

**Comment by jtackm** [comment] 2021-05-25 15:31
Thanks a lot for the quick help! For completeness, I got this file as-is from the NCBI SRA, so seems they don't always provide 100% fool-proof fastq.

**Comment by mashu** [comment] 2021-07-13 06:06
I was going to open an issue about this, indeed BioPython can read those FASTA files, while FASTX does not. The issue was white space at the end of one sequences. Perhaps adding simple **strip(..)** around the line would suffice?

**Comment by jakobnissen** [comment] 2021-07-13 07:47
This is already fixed on master. Making a new release since we have fixed numerous bugs the last year, but not released a new version of FASTX.

**Closed by jakobnissen** 2021-07-13 07:47 UTC
